/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Commentators {
  commentators: Commentator[];
  overrides: {
    should_override: boolean;
    override: {
      id: string;
      smash_gg_id: string;
      name: string;
      team: string;
      gamertag: string;
      country: string;
      twitter: string;
    };
  }[];
}
export interface Commentator {
  player_id: string;
}
