/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Players = {
  id: string;
  smash_gg_id?: number;
  name: string;
  team?: string;
  gamer_tag: string;
  country: string;
  twitter_handle?: string;
}[];
